import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { Check, ChevronLeft, ChevronRight, Copy, Mail, MessageCircle, Pencil, Search, Send, UserPlus, UsersRound } from "lucide-react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { api } from "../services/api";
import { useAppData } from "../providers/AppDataProvider";
import type { Message, Profile } from "../types";
import { Badge, Button, Card, Drawer, DrawerFooter, DrawerHeader, EmptyState, FormHint, FormSection, PageHeader, SegmentedControl, Skeleton } from "../components/ui";

const initials = (name: string) => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
export function Avatar({ profile, size = "normal" }: { profile: Pick<Profile, "displayName" | "avatarUrl">; size?: "small" | "normal" | "large" }) {
  return profile.avatarUrl ? <img className={`profile-avatar ${size}`} src={profile.avatarUrl} alt="" /> : <span className={`profile-avatar ${size}`}>{initials(profile.displayName)}</span>;
}
function PersonLink({ profile, children, className = "" }: { profile: Profile; children: React.ReactNode; className?: string }) {
  const navigate = useNavigate();
  return <button className={className} onClick={() => navigate(`/u/${profile.username}`)}>{children}</button>;
}
export function ProfilePage({ publicProfile = false }: { publicProfile?: boolean }) {
  const { username } = useParams();
  const navigate = useNavigate();
  const { profile: ownProfile, friends, friendRequests, conversations, groups, loading, error, refresh, pending, updateProfile, checkUsername, sendFriendRequest, acceptFriendRequest, declineFriendRequest, removeFriend, openDirectConversation } = useAppData();
  const [profile, setProfile] = useState<Profile | null>(publicProfile ? null : ownProfile);
  const [publicLoading, setPublicLoading] = useState(publicProfile);
  const [publicError, setPublicError] = useState(false);
  const [editing, setEditing] = useState(false);
  const [removing, setRemoving] = useState(false);
  const [draft, setDraft] = useState({ displayName: ownProfile?.displayName ?? "", username: ownProfile?.username ?? "", bio: ownProfile?.bio ?? "" });
  const [availability, setAvailability] = useState<{ available: boolean; message?: string } | null>(null);
  const [copied, setCopied] = useState(false);
  const [saveError, setSaveError] = useState("");
  useEffect(() => { if (!publicProfile) { setProfile(ownProfile); if (!editing) setDraft({ displayName: ownProfile?.displayName ?? "", username: ownProfile?.username ?? "", bio: ownProfile?.bio ?? "" }); return; } if (username) { setPublicLoading(true); setPublicError(false); void api.getUser(username).then(setProfile).catch(() => { setProfile(null); setPublicError(true); }).finally(() => setPublicLoading(false)); } }, [ownProfile, publicProfile, username, editing]);
  useEffect(() => { if (!editing || draft.username === ownProfile?.username) { setAvailability(null); return; } const timeout = window.setTimeout(() => void checkUsername(draft.username).then(setAvailability).catch(() => setAvailability({ available: false, message: "Não foi possível verificar agora." })), 320); return () => window.clearTimeout(timeout); }, [draft.username, editing, ownProfile?.username, checkUsername]);
  if ((loading && !profile) || publicLoading) return <ProfileSkeleton />;
  if (!profile) return publicError ? <EmptyState title="Perfil não encontrado" detail="Esta pessoa pode ter alterado o @username." /> : <div className="profile-error"><strong>Não foi possível carregar seu perfil.</strong><Button onClick={() => void refresh()}>Tentar novamente</Button></div>;
  const isOwn = profile.id === ownProfile?.id;
  const request = friendRequests.find((item) => item.profile.id === profile.id);
  const relation = isOwn ? "SELF" : friends.some((item) => item.id === profile.id) ? "FRIENDS" : request?.direction === "SENT" ? "SENT" : request?.direction === "RECEIVED" ? "RECEIVED" : "NONE";
  const message = async () => { const conversation = await openDirectConversation(profile.id); navigate(`/social?tab=conversations&conversation=${conversation.id}`); };
  const profileGroups = groups.filter((group) => group.members.some((member) => member.userId === profile.id && member.status === "ACTIVE"));
  const pendingRequests = friendRequests.filter((item) => item.direction === "RECEIVED").length;
  const unreadConversations = conversations.reduce((total, item) => total + item.unreadCount, 0);
  const since = new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric" }).format(new Date(profile.createdAt));
  const copy = async (value: string) => { try { await navigator.clipboard?.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1300); } catch { setCopied(false); } };
  const typeLabel: Record<string, string> = { TRIP: "Viagem", EVENT: "Evento", HOUSE: "Casa", GIFT: "Presente", COUPLE: "Casal", GOAL: "Meta", OTHER: "Grupo" };
  return <div className="profile-page">
    {!isOwn && <button className="back-link" onClick={() => navigate(-1)}>← Voltar</button>}
    <Card className="profile-hero"><Avatar profile={profile} size="large" /><div className="profile-identity"><h1>{profile.displayName}</h1><button className="username-copy selectable" aria-label="Copiar nome de usuário" onClick={() => void copy(`@${profile.username}`)}><span>@{profile.username}</span><Copy size={14} /><em>{copied ? "Copiado" : ""}</em></button>{profile.bio ? <p className="selectable">{profile.bio}</p> : isOwn ? <button className="profile-add-bio" onClick={() => setEditing(true)}>Conte um pouco sobre você <span>Adicionar descrição</span></button> : null}{isOwn && <div className="profile-summary"><button onClick={() => navigate("/social?tab=friends")}>{friends.length} amigo{friends.length === 1 ? "" : "s"}</button><i>·</i><button onClick={() => navigate("/groups")}>{profileGroups.length} grupo{profileGroups.length === 1 ? "" : "s"}</button>{conversations.length > 0 && <><i>·</i><button onClick={() => navigate("/social?tab=conversations")}>{conversations.length} conversa{conversations.length === 1 ? "" : "s"}</button></>}</div>}{!isOwn && <small className="public-profile-note">{relation === "FRIENDS" ? "Vocês são amigos" : "Perfil público"}</small>}</div><div className="profile-actions">{isOwn ? <Button onClick={() => setEditing(true)}><Pencil size={16} />Editar perfil</Button> : relation === "NONE" ? <Button loading={pending.mutation} onClick={() => void sendFriendRequest(profile.id)}><UserPlus size={16} />Adicionar amigo</Button> : relation === "SENT" ? <Button variant="secondary" disabled>Solicitação enviada</Button> : relation === "RECEIVED" ? <><Button loading={pending.mutation} onClick={() => request && void acceptFriendRequest(request.id)}><Check size={16} />Aceitar</Button><Button variant="secondary" onClick={() => request && void declineFriendRequest(request.id)}>Recusar</Button></> : <><Button onClick={() => void message()}><MessageCircle size={16} />Mensagem</Button><Button variant="secondary" onClick={() => setRemoving(true)}>Amigos</Button></>}</div></Card>
    {isOwn && <><div className="profile-detail-grid"><Card className="profile-detail-card"><p className="eyebrow">Sobre</p><h2>Sua presença</h2><div className="profile-detail-line"><span>No Cofrin desde</span><strong>{since}</strong></div><button className="profile-security-link" onClick={() => navigate("/settings?tab=security")}>Gerenciar segurança <ChevronRight size={15} /></button></Card><Card className="profile-detail-card profile-social-card"><p className="eyebrow">Social</p><h2>Suas conexões</h2><button className="profile-social-row" onClick={() => navigate("/social?tab=friends")}><span>Amigos</span><strong>{friends.length}</strong><ChevronRight size={16} /></button>{pendingRequests > 0 ? <button className="profile-social-row" onClick={() => navigate("/social?tab=requests")}><span>Solicitações</span><strong>{pendingRequests}</strong><ChevronRight size={16} /></button> : <p className="profile-social-empty">Nenhuma solicitação pendente</p>}{unreadConversations > 0 ? <button className="profile-social-row" onClick={() => navigate("/social?tab=conversations")}><span>Conversas</span><strong>{unreadConversations}</strong><ChevronRight size={16} /></button> : conversations.length > 0 ? <button className="profile-social-row" onClick={() => navigate("/social?tab=conversations")}><span>Conversas</span><strong>{conversations.length}</strong><ChevronRight size={16} /></button> : null}</Card></div><section className="profile-groups-section"><div className="profile-section-title"><div><p className="eyebrow">Participação</p><h2>Grupos compartilhados</h2></div>{profileGroups.length > 3 && <button onClick={() => navigate("/groups")}>Ver todos os grupos <ChevronRight size={15} /></button>}</div>{profileGroups.length ? <Card className="profile-groups-list">{profileGroups.slice(0, 3).map((group) => <button key={group.id} className="profile-group-row" onClick={() => navigate(`/groups/${group.id}`)}><span className="profile-group-type">{typeLabel[group.type]}</span><span><strong>{group.name}</strong><small>{group.members.filter((member) => member.status === "ACTIVE").length} participantes</small></span><ChevronRight size={17} /></button>)}</Card> : <Card className="profile-groups-empty"><p>Você ainda não participa de nenhum planejamento compartilhado.</p><Button variant="secondary" onClick={() => navigate("/groups")}>Ver grupos</Button></Card>}</section><Card className="profile-account"><div><p className="eyebrow">Conta</p><h2>Informações da conta</h2></div><div className="profile-account-grid"><div><span>E-mail</span><button className="selectable account-copy" onClick={() => profile.email && void copy(profile.email)}><Mail size={14} />{profile.email}<Copy size={13} /></button></div><div><span>Conta criada</span><strong>{since}</strong></div></div></Card></>}
    <Drawer open={editing} onClose={() => { setEditing(false); setSaveError(""); }}><DrawerHeader eyebrow="Perfil" title="Editar perfil" description="Atualize como você aparece nas interações do Cofrin." /><form onSubmit={async (event) => { event.preventDefault(); if (availability && !availability.available) return; setSaveError(""); try { await updateProfile(draft); setEditing(false); } catch { setSaveError("Não foi possível salvar agora. Seus dados continuam aqui."); } }}><div className="profile-preview"><Avatar profile={{ displayName: draft.displayName || "Seu nome" }} /><div><strong>{draft.displayName || "Seu nome"}</strong><small>@{draft.username.replace(/^@/, "").toLowerCase()}</small></div></div><FormSection title="Identidade"><div className="form-field"><label>Nome de exibição</label><input value={draft.displayName} onChange={(event) => setDraft({ ...draft, displayName: event.target.value })} /></div><FormHint>O avatar continua usando suas iniciais nesta versão.</FormHint></FormSection><FormSection title="Identificador"><div className="form-field"><label>@username</label><input value={draft.username} onChange={(event) => setDraft({ ...draft, username: event.target.value.replace(/^@+/, "") })} /></div>{draft.username !== ownProfile?.username && <FormHint>{availability ? availability.available ? "Disponível" : availability.message : "Verificando..."}</FormHint>}</FormSection><FormSection title="Sobre você"><div className="form-field"><label>Bio</label><textarea maxLength={160} value={draft.bio} onChange={(event) => setDraft({ ...draft, bio: event.target.value })} /><FormHint>{draft.bio.length} / 160</FormHint></div></FormSection>{saveError && <p className="form-error">{saveError}</p>}<DrawerFooter onCancel={() => { setEditing(false); setSaveError(""); }} submitLabel="Salvar alterações" loading={pending.mutation} /></form></Drawer>
    <Drawer open={removing} onClose={() => setRemoving(false)}><DrawerHeader eyebrow="Amizade" title={`Remover ${profile.displayName} dos amigos?`} description="Ela deixará de aparecer na sua lista. Os grupos compartilhados existentes não serão apagados." /><DrawerFooter onCancel={() => setRemoving(false)} submitLabel="Remover amizade" loading={pending.mutation} /><Button className="budget-delete" variant="danger" onClick={async () => { await removeFriend(profile.id); setRemoving(false); navigate("/social"); }}>Confirmar remoção</Button></Drawer>
  </div>;
}
function ProfileSkeleton() { return <div className="profile-page profile-skeleton"><Skeleton lines={4} /><div className="profile-detail-grid"><Skeleton lines={3} /><Skeleton lines={3} /></div><Skeleton lines={4} /></div>; }

export function SocialPage() {
  const navigate = useNavigate();
  const [params, setParams] = useSearchParams();
  const { friends, friendRequests, conversations, pending, searchPeople, sendFriendRequest, acceptFriendRequest, declineFriendRequest, cancelFriendRequest, openDirectConversation } = useAppData();
  const tab = (params.get("tab") ?? "friends") as "friends" | "requests" | "conversations";
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<(Profile & { relationship: "NONE" | "SENT" | "RECEIVED" | "FRIENDS" })[]>([]);
  const [searching, setSearching] = useState(false);
  useEffect(() => { if (query.trim().length < 2) { setResults([]); return; } setSearching(true); const timeout = window.setTimeout(() => void searchPeople(query).then(setResults).finally(() => setSearching(false)), 280); return () => window.clearTimeout(timeout); }, [query, searchPeople]);
  const setTab = (value: typeof tab) => { const next = new URLSearchParams(params); next.set("tab", value); if (value !== "conversations") next.delete("conversation"); setParams(next); };
  const received = friendRequests.filter((item) => item.direction === "RECEIVED");
  return <div className="social-page"><PageHeader eyebrow="Conexões" title="Social" description="Encontre pessoas, mantenha seus contatos e converse." /><SegmentedControl value={tab} onChange={setTab} options={[{ value: "friends", label: "Amigos" }, { value: "requests", label: `Solicitações${received.length ? ` (${received.length})` : ""}`, tone: "gold" }, { value: "conversations", label: "Conversas" }]} />
    {tab === "friends" && <section className="social-section"><div className="people-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nome ou @" /></div>{searching && <p className="muted-status">Buscando pessoas...</p>}{query.trim().length >= 2 && !searching && <div className="search-results">{results.length ? results.map((person) => <PersonResult key={person.id} profile={person} onSend={() => void sendFriendRequest(person.id)} onAccept={() => { const request = friendRequests.find((item) => item.profile.id === person.id); if (request) void acceptFriendRequest(request.id); }} />) : <EmptyState title="Ninguém encontrado" detail="Tente outro nome ou @username." />}</div>}<Card className="social-list"><div className="section-heading"><div><h2>Seus amigos</h2><p>{friends.length ? `${friends.length} pessoa${friends.length === 1 ? "" : "s"} para planejar junto.` : "Busque uma pessoa pelo @ para começar."}</p></div></div>{friends.length ? friends.map((person) => <PersonRow key={person.id} profile={person} action={<Button onClick={async (event) => { event.stopPropagation(); const conversation = await openDirectConversation(person.id); navigate(`/social?tab=conversations&conversation=${conversation.id}`); }}><MessageCircle size={15} />Mensagem</Button>} />) : <EmptyState title="Você ainda não adicionou ninguém" detail="Busque uma pessoa pelo @ para começar." />}</Card></section>}
    {tab === "requests" && <Card className="social-list">{friendRequests.length ? friendRequests.map((request) => <PersonRow key={request.id} profile={request.profile} detail={request.direction === "RECEIVED" ? "Quer adicionar você" : "Solicitação enviada"} action={request.direction === "RECEIVED" ? <div className="row-actions"><Button variant="secondary" onClick={(event) => { event.stopPropagation(); void declineFriendRequest(request.id); }}>Recusar</Button><Button loading={pending.mutation} onClick={(event) => { event.stopPropagation(); void acceptFriendRequest(request.id); }}>Aceitar</Button></div> : <Button variant="secondary" onClick={(event) => { event.stopPropagation(); void cancelFriendRequest(request.id); }}>Cancelar</Button>} />) : <EmptyState title="Nenhuma solicitação pendente" detail="Novos pedidos de amizade aparecerão aqui." />}</Card>}
    {tab === "conversations" && <ConversationLayout />}</div>;
}
function PersonResult({ profile, onSend, onAccept }: { profile: Profile & { relationship: "NONE" | "SENT" | "RECEIVED" | "FRIENDS" }; onSend: () => void; onAccept: () => void }) { const navigate = useNavigate(); return <div className="person-result" onClick={() => navigate(`/u/${profile.username}`)}><Avatar profile={profile} /><div><strong>{profile.displayName}</strong><small>@{profile.username}</small></div>{profile.relationship === "NONE" ? <Button onClick={(event) => { event.stopPropagation(); onSend(); }}>Adicionar</Button> : profile.relationship === "RECEIVED" ? <Button onClick={(event) => { event.stopPropagation(); onAccept(); }}>Aceitar</Button> : <Badge tone={profile.relationship === "FRIENDS" ? "green" : "neutral"}>{profile.relationship === "FRIENDS" ? "Amigos" : "Enviado"}</Badge>}</div>; }
function PersonRow({ profile, detail, action }: { profile: Profile; detail?: string; action: React.ReactNode }) { const navigate = useNavigate(); return <div className="person-row" onClick={() => navigate(`/u/${profile.username}`)}><Avatar profile={profile} /><div><strong>{profile.displayName}</strong><small>@{profile.username}{detail ? ` · ${detail}` : ""}</small></div>{action}</div>; }
function ConversationLayout() { const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const { conversations, getMessages, sendConversationMessage, markConversationRead, pending, profile, friends } = useAppData(); const selectedId = params.get("conversation") ?? conversations[0]?.id; const selected = conversations.find((item) => item.id === selectedId); const [messages, setMessages] = useState<Message[]>([]); const [text, setText] = useState(""); const scroll = useRef<HTMLDivElement>(null); useEffect(() => { if (!selectedId) return; void getMessages(selectedId).then((items) => { setMessages(items); void markConversationRead(selectedId); }); }, [selectedId]); useEffect(() => { scroll.current?.scrollTo({ top: scroll.current.scrollHeight }); }, [messages]); const people = useMemo(() => new Map([profile, ...friends].filter(Boolean).map((item) => [item!.id, item!])), [profile, friends]); if (!conversations.length) return <EmptyState title="Nenhuma conversa ainda" detail="Envie uma mensagem para um amigo ou use a conversa de um grupo." />; const submit = async (event: FormEvent) => { event.preventDefault(); if (!selected || !text.trim()) return; const message = await sendConversationMessage(selected.id, text); setMessages((items) => [...items, message]); setText(""); };
  return <div className={`conversation-layout ${selected ? "has-selection" : ""}`}><aside className="conversation-list"><p className="eyebrow">Conversas</p>{conversations.map((conversation) => <button className={`conversation-list-item ${conversation.id === selectedId ? "active" : ""}`} key={conversation.id} onClick={() => { const next = new URLSearchParams(params); next.set("conversation", conversation.id); setParams(next); }}><span className="conversation-mini-avatar">{conversation.type === "GROUP" ? <UsersRound size={16} /> : initials(conversation.title)}</span><span><strong>{conversation.title}</strong><small>{conversation.lastMessage ? `${conversation.lastMessage.senderId === profile?.id ? "Você: " : ""}${conversation.lastMessage.content}` : "Conversa iniciada"}</small></span>{conversation.unreadCount > 0 && <i>{conversation.unreadCount}</i>}</button>)}</aside>{selected && <section className="conversation-panel"><button className="conversation-back" onClick={() => { const next = new URLSearchParams(params); next.delete("conversation"); setParams(next); }}><ChevronLeft size={16} />Conversas</button><button className="conversation-header" onClick={() => navigate(selected.type === "GROUP" ? `/groups/${selected.groupId}` : `/u/${people.get(selected.avatarUserId ?? "")?.username ?? ""}`)}><span className="conversation-mini-avatar">{selected.type === "GROUP" ? <UsersRound size={17} /> : initials(selected.title)}</span><span><strong>{selected.title}</strong><small>{selected.subtitle}</small></span><ChevronRight size={16} /></button><div className="messages" ref={scroll}>{messages.length ? messages.map((message, index) => { const own = message.senderId === profile?.id; const sender = people.get(message.senderId); const previous = messages[index - 1]; const showName = !own && previous?.senderId !== message.senderId; return <div className={`message ${own ? "own" : ""}`} key={message.id}>{showName && <small>{sender?.displayName ?? "Participante"}</small>}<p>{message.content}</p><time>{new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit" }).format(new Date(message.createdAt))}</time></div>; }) : <EmptyState title="Ainda não há mensagens" detail="Diga oi para iniciar a conversa." />}</div><form className="message-composer" onSubmit={(event) => void submit(event)}><textarea value={text} maxLength={2000} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); (event.currentTarget.form as HTMLFormElement)?.requestSubmit(); } }} placeholder="Escreva uma mensagem..." /><Button type="submit" loading={pending.mutation} disabled={!text.trim()} aria-label="Enviar"><Send size={16} /></Button></form></section>}</div>; }
export function GroupConversationPanel({ groupId }: { groupId: string }) {
  const { getGroupConversation, getMessages, sendConversationMessage, pending, profile } = useAppData();
  const [conversationId, setConversationId] = useState<string | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [text, setText] = useState("");
  useEffect(() => { void getGroupConversation(groupId).then(async (conversation) => { setConversationId(conversation.id); setMessages(await getMessages(conversation.id)); }); }, [groupId]);
  if (!conversationId) return <p className="muted-status">Preparando conversa...</p>;
  return <div className="group-conversation"><div className="messages">{messages.length ? messages.map((message) => <div className={`message ${message.senderId === profile?.id ? "own" : ""}`} key={message.id}><p>{message.content}</p><time>{new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit" }).format(new Date(message.createdAt))}</time></div>) : <EmptyState title="Ainda não há mensagens" detail="Inicie a conversa sobre o planejamento." />}</div><form className="message-composer" onSubmit={async (event) => { event.preventDefault(); if (!text.trim()) return; const message = await sendConversationMessage(conversationId, text); setMessages((items) => [...items, message]); setText(""); }}><textarea value={text} maxLength={2000} onChange={(event) => setText(event.target.value)} placeholder="Escreva para o grupo..." /><Button type="submit" loading={pending.mutation} disabled={!text.trim()}><Send size={16} />Enviar</Button></form></div>;
}
