-- HISTORICAL MARKER ONLY. Do not apply to a new installation.
-- The former Supabase-Auth social migration was retired when Cofrin-owned
-- authentication became authoritative. Use ../schema.sql for fresh databases.
